export const fileInput = document.querySelector('.file-input')
export const chooseImgBtn = document.querySelector('.choose-img')
export const previewImg = document.querySelector('.preview-img img')
export const filterOptions = document.querySelectorAll('.filter button')
export const filterName = document.querySelector('.filter-info .name')
export const filterSlider = document.querySelector('.slider input')
export const filterValue = document.querySelector('.slider .value')
export const resetBtn = document.querySelector('.reset-filter')
export const saveFilterBtn = document.querySelector('.save-filter')
export const formCreateNewPost = document.getElementById('formCreateNewPost')

export const detailModal = document.getElementById('postDetailModal')
export const closeDetailBtn = document.getElementById('closeDetailBtn')
export const detailPost = document.querySelector('.detail-post')

export const createModal = document.getElementById('createNewPostModal')
export const closeCreateBtn = document.getElementById('closeCreateBtn')
export const detailCreate = document.querySelector('.create-new-content')
export const newPostBtn = document.querySelector('.nav__create-post')
